name: Build and test
on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "main"
      - "release/v[0-9]**"
  workflow_dispatch:
permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: "^1.21"
      - name: Display go version
        run: go version
      - name: Run all tests
        run: make test-all
      - uses: technote-space/get-diff-action@v6.1.2
        id: git_diff
        with:
          PATTERNS: |
            **/*.go
            go.mod
            go.sum
            **/go.mod
            **/go.sum
            **/Makefile
            Makefile
        ###################
        #### Build App ####
        ###################
      - name: Build demo app # to ensure everything compiles
        if: env.GIT_DIFF
        run: make build
      - name: Build demo app # execute all tests
        if: env.GIT_DIFF
        run: make test